name: pybuilder
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-stable:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-10.15
          - macos-11
        python-version:
          - '3.10'
          - '3.9'
          - '3.8'
          - '3.7'
          - '3.6'
          - 'pypy-3.7'
        with-venv:
          - 'true'
          - 'false'
        with-homebrew:
          - 'true'
          - 'false'
    env:
      DEPLOY_BRANCHES: "refs/heads/master"
      DEPLOY_PYTHONS: "3.9"
      DEPLOY_OSES: "Linux"
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - shell: bash
        if: |
          contains(env.DEPLOY_OSES, runner.os) &&
          contains(env.DEPLOY_PYTHONS, matrix.python-version) &&
          contains(env.DEPLOY_BRANCHES, github.ref) &&
          matrix.with-venv == 'true'
        run: |
          echo "PYB_EXTRA_ARGS='+upload'" >> $GITHUB_ENV
      - uses: pybuilder/build@master
        if: |
          !(matrix.with-homebrew == 'true' && runner.os != 'macOS' ||
            matrix.with-homebrew == 'true' && runner.os == 'macOS' &&
            (matrix.python-version == '3.6' ||
             contains(matrix.python-version, '-rc') ||
             contains(matrix.python-version, '-b') ||
             contains(matrix.python-version, 'pypy-')
            )
           )
        with:
          python-version: ${{ matrix.python-version }}
          homebrew-python: ${{ matrix.with-homebrew }}
          with-venv: ${{ matrix.with-venv }}
          install-pyb: 'false'
          pyb-command: $PYTHON build.py
          pyb-extra-args: +install ${{ env.PYB_EXTRA_ARGS }}
  build-stable-summary:
    if: success() || failure()
    runs-on: ubuntu-latest
    name: Build Stable Summary
    needs: build-stable
    steps:
      - name: Check build matrix status
        if: needs.build-stable.result != 'success'
        run: exit 1
